version: '3.9'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest-api:
    container_name: nest-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
volumes:
  postgres-data:
